---
title: "Exercise 1.5: Documenting Projects with README Files"
author: "David Souto"
date: "`r Sys.Date()`"
output: html_document
---

In this section, we will learn how to create and format a README file using R Markdown. README files are essential for documenting your projects and providing information to users and collaborators. 

There are several points where you want one.

At a minimum you want one within the project folder, describing the project, what is needed to reproduce the analysis, etc.

Other options: 

In the data folder: Describe how the data is organized

In the analysis folder: Describe how to run the analysis

### Create a README.Rmd 

1. Open RStudio.
2. Navigate to File > New File > Markdown file and (not R Markdown, which would create an .Rmd file) 
3. Save as README (.md)

### Experiment with Headings

Copy the following text into your README file

These are different headings

### Heading 3: Big title

## Heading 2: Medium

# Heading 1: Small

Link to [something cool](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

### Preview the file (HTML format)

- In RStudio, click on the **Preview** button, or " select **PreviewHTML**, or just **Preview**
- This will generate a formatted version of the document that should pop up and could also be opened in any web browser and will generate
and .html file in the working directory

### Create a bullet Point List

Add a bullet point list to your README file using the following syntax:
markdown

* Point 1

* Point 2

After adding the bullet points, click Knit to see the formatted list in the output document.

### Integration with GitHub

If you visit the [workshop repository](https://github.com/DavidSouto/ReproScience-Workshop) you will that GitHub shows the formatted contents of the README.md project file. 

Note that R Markdown (the file type of the exercise notebooks) extends this format to R code but is very similar in its basic function. On the other hand it isn't recognized by GitHub.

By using R Markdown, you can create a dynamic and reproducible document that combines narrative text with code. More on this in the second session (Exercise 2.4)

Key Takeaways 

Creating a well-documented README file is essential for any project. It serves as the first point of contact for users and collaborators, providing them with the necessary information to understand and use your work effectively. 


